inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.1
  Include:
  - '**/Rakefile'
  - '**/config.ru'
  Exclude:
  - "vendor/**/*"
  - 'config/**/*'
  - 'script/**/*'
  - "db/schema.rb"
AsciiComments:
  Enabled: false
Lambda:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
AccessorMethodName:
  Enabled: false
Documentation:
  Enabled: false
AndOr:
  Enabled: false
Rails:
  Enabled: true
inherit_gem:
  rubocop-rails_config:
  - config/rails.yml
Style/FrozenStringLiteralComment:
  Enabled: false
StringLiterals:
  EnforcedStyle: single_quotes
